### ISSUE TITLE
hello_world example: can't python bootstrap.py

### ISSUE THREAD

**Issue by procmail** [plone/documentation#232]
On this the page http://docs.plone.org/develop/addons/helloworld/environment/plone.html it says:
`../bin/python bootstrap.py`

However, this always fails. Error log here:
http://pastebin.com/G2FDabDp

```
(env-27)➜  hello_world  ls
README.txt   bootstrap.py buildout.cfg src          var
(env-27)➜  hello_world  cd hello_world
(env-27)➜  hello_world  ../bin/python bootstrap.py
Traceback (most recent call last):
  File "bootstrap.py", line 70, in <module>
    exec urllib2.urlopen(setup_url).read() in ez
  File "/Users/eric/python_dev/buildout.python/parts/opt/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/eric/python_dev/buildout.python/parts/opt/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/Users/eric/python_dev/buildout.python/parts/opt/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/eric/python_dev/buildout.python/parts/opt/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/Users/eric/python_dev/buildout.python/parts/opt/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/Users/eric/python_dev/buildout.python/parts/opt/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Users/eric/python_dev/buildout.python/parts/opt/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/Users/eric/python_dev/buildout.python/parts/opt/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/eric/python_dev/buildout.python/parts/opt/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/Users/eric/python_dev/buildout.python/parts/opt/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/Users/eric/python_dev/buildout.python/parts/opt/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by svx** [comment]
Yes, we know, we are already working on this: https://github.com/plone/documentation/issues/193

Thanks for reporting !!

Btw you really should not use paster and zopeskel anymore, please move over to: https://github.com/plone/bobtemplates.plone and use bobtemplates.
 
Thanks !

**Comment by procmail** [comment]
Thanks for the link. I'll have a look at bobtemplates.

I'm a newcomer to Plone as well as buildout, so this is all very confusing to me. As it is, I'm not sure which part of the hello_world tutorial to substitute with bobtemplates.

I understand everyone's busy getting ready for Plone 5, and if Plone 5's docs are ready, I can start learning and beta-testing from there instead.

**Comment by gforcada** [comment]
@procmail welcome to Plone!

If you are new maybe it will be easier for you to read and follow the Plone training: http://plone-training.readthedocs.org/en/latest/

There you will have an easy and well documented learning path into Plone.

**Comment by procmail** [comment]
Thank you!

**Comment by fulv** [comment]
Also, take a look at this:
https://medium.com/@timostollenwerk/getting-started-with-plone-testing-13a1a3f4ccc4
I believe it addresses the

**Comment by svx** [comment]
We should fine a way to make sure that examples are actually working, not sure yet how to hook up examples use in the docs to jenkins or travis.

Anyone ?

**Comment by jensens** [comment]
at least nowadays the documentation points to bobtemplates usage, the old hello world is gone.
